### ISSUE TITLE
Docker Setup for Mac

### ISSUE THREAD

**Issue by Benned-H** [Benned-H/champ#2]
To separate concerns, I'll allow #1 to merge without addressing a Docker container for macOS.

Check back once on a Mac:

```
  base-gui-mac-os: # Base service supporting GUIs on macOS hosts
    extends:
      service: base-cli

    environment:
      # Environment variables to support in-container GUIs on a macOS host
      - DISPLAY=docker.for.mac.host.internal:0

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 Unix socket to support GUIs
  ```
